title: Advanced Developer Experiments
email: mikopet@gmail.com
author: Peter MIKOLA
description: Some intriguing adventure on the field of development
avatar: https://avatars3.githubusercontent.com/u/4664202?v=4
baseurl: ""
url: "https://mikopet.dev"
twitter_username: Mikopet
github_username:  Mikopet

plugins:
  - jekyll-feed
  - jekyll-sitemap

footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: Mikopet
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: Mikopet
  stackoverflow: users/2488588/mikopet
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

excerpt_separator: "---"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - vendor
